title: Your awesome title
author: Gayatri Rajgor
email: gayatrirajgor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Currently a final year software engineering student.
# social links
github_username:  gayatrirajgor # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
